# Generated by Django 4.2.10 on 2024-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="deleedAt",
        ),
        migrations.AddField(
            model_name="test",
            name="deletedAt",
            field=models.DateTimeField(null=True),
        ),
    ]
