# Generated by Django 4.2.10 on 2024-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_test_deleedat_test_deletedat"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
