# Generated by Django 4.2.10 on 2024-03-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_test_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="testType",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
