# Generated by Django 4.2.10 on 2024-04-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_test_testtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("runAt", models.DateTimeField(null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("deletedAt", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contains",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "testID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.test"
                    ),
                ),
                (
                    "testPlanID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.testplan"
                    ),
                ),
            ],
        ),
    ]
