# Generated by Django 4.2.10 on 2024-04-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_testplan_contains"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testplan",
            name="runAt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
