# Generated by Django 4.2.10 on 2024-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_testexecution_testplanexecution_testimage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testexecution",
            name="referenceID",
        ),
        migrations.AddField(
            model_name="test",
            name="referenceID",
            field=models.IntegerField(null=True),
        ),
    ]
