# Generated by Django 4.2.10 on 2024-05-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_test_executions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testexecution",
            name="testPlanExecutionID",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.testplanexecution",
            ),
        ),
    ]
