# Generated by Django 4.2.10 on 2024-05-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_testimage_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testexecution",
            name="bugs",
            field=models.IntegerField(default=0),
        ),
    ]
